### ISSUE TITLE
Issue with sol:lint and Github action

### ISSUE THREAD

**Issue by Sarimarcus** [PaulRBerg/hardhat-template#154] opened 2023-02-19 19:59 UTC
Hello Paul !  First of all, thanks for this template. 
I was about to give it a try, I'm learning Solidity, but have some coding background.
I've created my first project using your template, and I'm facing this error when running : 

{code}
yarn lint:sol
{code}

it returns :  

{code}
contracts/Greeter.sol
   4:1  error    Unexpected import of console file                                                               no-console
   4:1  warning  global import of path hardhat/console.sol is not allowed. Specify names to import individually  no-global-import
  12:9  error    Unexpected console statement                                                                    no-console
  21:9  error    Unexpected console statement                                                                    no-console

✖ 4 problems (3 errors, 1 warning)
{code}

It's about the import of : `import "hardhat/console.sol";`

Github Action is returning me the same error on initializing the projet : https://gyazo.com/0a304d587623246751fff30b0e64c55a

When I compile, everything is OK, I have the logs from Hardhat.

I've also seen this post and your answer : https://ethereum.stackexchange.com/questions/111568/hardhat-console-cant-be-resolved-in-vscode, but the solution you are giving is not fixing the issue. 

I'm not sure whats the best solution.

Thank you for your help.

**Comment by PaulRBerg** [comment] 2023-02-19 21:34
Hey @Sarimarcus, glad you like this template (by the way, have you seen my other [Foundry template](https://github.com/PaulRBerg/foundry-template)? nowadays, I recommend people to start with Foundry instead of Hardhat).

Thank you for creating this issue. The problem is with a recent release of Solhint (v3.4.0), which [added](https://github.com/protofire/solhint/blob/b39d897958ca7d859f9ab5e9b3ec6fbabfaaebc2/CHANGELOG.md) a rule that disallows the use of Hardhat's `console.sol`. But, of course, using console logs in testing is an entirely legitimate use case. Therefore, I have just disabled the rule in the template with this commit:

https://github.com/PaulRBerg/hardhat-template/commit/5efd748fcaf282f8cf1020c884714a7dd8077c41

This should address your problem, so I have closed this GitHub issue as completed. But please do let me know if you keep bumping into this even after disabling the `no-console` rule.

**Closed by PaulRBerg** 2023-02-19 21:34 UTC

**Comment by Sarimarcus** [comment] 2023-02-20 08:41
Thank you @PaulRBerg, I just have a warning now : 

{code}
contracts/Greeter.sol
  4:1  warning  global import of path hardhat/console.sol is not allowed. Specify names to import individually  no-global-import
{code}

I think it's manageable then. 

About Foundry, well I though Hardhat was the most used and fancy framework lately for Solidity development, but I imagine thinks ar emoving fast. I'll also try to give it a try.

Thanks again for the help

**Comment by PaulRBerg** [comment] 2023-02-20 10:10
> just have a warning now

Oh, yes. That is another recently introduced Solhint feature - I should have known about them after [tweeting](https://twitter.com/PaulRBerg/status/1626627614038163468) about them better, haha.

I have just pushed another commit to fix this warning - this time, the solution was not to disable the Solhint rule but rather to tackle the issue itself:

https://github.com/PaulRBerg/hardhat-template/commit/f6da16a232b9863b31940fb4254b18d156096efd

> About Foundry, well, I thought Hardhat was the most used and fancy framework lately for Solidity development,

Hardhat may have more users (because JavaScript is ubiquitous), but Foundry is, simply put, much better for Ethereum development. With Foundry, you write tests in Solidity! I highly recommend you give it a go.
